### ISSUE TITLE
Integrate into SoftHSM2 repo?

### ISSUE THREAD

**Issue by jschlyter** [disig/SoftHSM2-for-Windows#1]
Do you want us to merge this into the official SoftHSM2 repo? If so, please send a pull request and we'll take a look at it.

**Comment by jariq** [comment]
Thanks for asking but the current state is OK IMO because keeping packaging stuff in a separate repository is a common practice also in Fedora ([softhsm](http://pkgs.fedoraproject.org/cgit/softhsm.git)) and Debian ([softhsm2](http://anonscm.debian.org/cgit/pkg-nlnetlabs/softhsm2.git/)). However when it comes to the source code changes I will try to merge all of them just like I already did with opendnssec/SoftHSMv2#129.

**Comment by jschlyter** [comment]
OK. Thanks for your work - highly appreciated!
